//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class HoaDonDatMon
    {
        [Key]
        public int MaHD { get; set; }
        public Nullable<int> MaMon { get; set; }
        public Nullable<int> MaKH { get; set; }

        [DisplayName("Ngày đặt")]
        [Required(ErrorMessage = "Phải có {0}")]
        [DataType(DataType.DateTime, ErrorMessage = "Không đúng định dạng")] 
        public Nullable<System.DateTime> NgayDat { get; set; }

        [DisplayName("Số lượng")]
        [Required(ErrorMessage = "Phải có {0}")]
        [Range(0, int.MaxValue, ErrorMessage = "{0} phải lớn hơn {1}")]
        public Nullable<int> SoLuong { get; set; }

        [ForeignKey("MaKH")]    
        public virtual KhachHang KhachHang { get; set; }

        [ForeignKey("MaMon")]
        public virtual MonAn MonAn { get; set; }
    }
}
