//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.HoaDonDatMons = new HashSet<HoaDonDatMon>();
        }

        [Key]    
        public int MaKH { get; set; }

        [DisplayName("Họ tên")]
        [Required(ErrorMessage = "Phải có {0}")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "{0} có độ dài từ {2} đến {1} ký tự")]
        public string HoTen { get; set; }

        [DisplayName("Điện thoại")]
        [Required(ErrorMessage = "Phải có {0}")]
        [RegularExpression("(84|0[3|5|7|8|9])+([0-9]{8})", ErrorMessage = "Phải là {0}")]
        public string DienThoai { get; set; }

        [Required(ErrorMessage = "Phải có {0}")]
        [EmailAddress(ErrorMessage = "Phải là {0}")]
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonDatMon> HoaDonDatMons { get; set; }
    }
}
